spring:
  datasource:
    url: jdbc:mysql://192.168.1.14:3306/dms_test
    username: d1
    password: p1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
